server:
  port: 8093
spring:  cloud:    config:      server:
        bootstrap: false        git:          uri: https://github.com/mahendhar03/configuration_respository.git
          username: mahendhar0301@gmail.com
          password: Mahi@030119
          clone-on-start: true